# fly.toml app configuration file generated for nextchat-nieeda on 2025-02-17T12:41:36Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "yumeng-chatgpt"
primary_region = "hkg"

[env]
  BASE_URL = "https://dzqc.link/"

[build]

[http_service]
  auto_start_machines = false
  auto_stop_machines = false
  force_https = true
  internal_port = 3_000
  min_machines_running = 1
  processes = [ "app" ]

[[vm]]
  size = "shared-cpu-1x"
  memory_mb = 256
