# fly.toml app configuration file generated for yumeng-chatgpt on 2025-02-17T13:51:07Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'yumeng-chatgpt'
primary_region = 'lax'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
