# fly.toml app configuration file generated for nextchat-nieeda on 2025-02-17T12:41:36Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nextchat-nieeda'
primary_region = 'lax'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
